INSERT INTO USERS (email,username, password, enabled)VALUES ('aa@bb.cc','admin','$2a$10$soDKnoTm4BkaaRCFQkldsOCZDfCTSc0NBn0XvH9CL6nssg3UrB0Rm',1); -- u:admin p:123

INSERT INTO ROLES (ID,NAME) VALUES (1,'ROLE_USER');
INSERT INTO ROLES (ID,NAME) VALUES (2,'ROLE_ADMIN');

INSERT INTO USER_ROLES (USER_ID,ROLE_ID) VALUES (1,1);
INSERT INTO USER_ROLES (USER_ID,ROLE_ID) VALUES (1,2);
