CREATE TABLE USERS (
    ID INT(11) NOT NULL AUTO_INCREMENT,
    EMAIL VARCHAR(45) ,
    USERNAME VARCHAR(45) NOT NULL,
    PASSWORD VARCHAR(64) NOT NULL,
    ENABLED TINYINT(4) DEFAULT NULL,
    PRIMARY KEY (ID),
    UNIQUE KEY EMAIL_UNIQUE (EMAIL)
);

CREATE TABLE ROLES (
    ID INT(11) NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(45) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE USER_ROLES (
    USER_ID INT(11) NOT NULL,
    ROLE_ID INT(11) NOT NULL,
    CONSTRAINT ROLE_FK FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ID),
    CONSTRAINT USER_FK FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);
