CREATE DATABASE DEMODB;


DROP TABLE IF EXISTS DEMODB.USERINFO;

CREATE TABLE DEMODB.USERINFO
(
    ID       INT,
    ISIM     VARCHAR(100),
    EMAIL    VARCHAR(50),
    PASSWORD VARCHAR(16),
    STATUS   INT
);

-- SELECT * FROM DEMODB.USERINFO;
