CREATE TABLE CUSTOMERS (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(252),
    CREATE_DATE TIMESTAMP,
    PRIMARY KEY (ID)
);

CREATE TABLE ORDERS (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    CUSTOMER_ID BIGINT,
    PRODUCT_NAME VARCHAR(128),
    PRICE BIGINT,
    PRIMARY KEY (ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID)
);

CREATE TABLE TODOS (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    TITLE VARCHAR(128),
    DESCRIPTION VARCHAR(128),
    DELETED NUMBER(1),
    PRIMARY KEY (ID)
);

CREATE TABLE NOTIFICATION (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    FIRST_NAME VARCHAR(25),
    LAST_NAME VARCHAR(25),
    CONTENT VARCHAR(25),
    PRIMARY KEY (ID)
);

CREATE TABLE SMS_NOTIFICATION (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    PHONE_NUMBER VARCHAR(25),
    PRIMARY KEY (ID)
);

CREATE TABLE EMAIL_NOTIFICATION (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    EMAIL VARCHAR(100),
    PRIMARY KEY (ID)
);
