INSERT INTO CUSTOMERS (ID, NAME, CREATE_DATE) VALUES (1, 'Ahmet',  CURRENT_TIMESTAMP);
INSERT INTO CUSTOMERS (ID, NAME, CREATE_DATE) VALUES (2, 'Mehmet',  CURRENT_TIMESTAMP);
INSERT INTO CUSTOMERS (ID, NAME, CREATE_DATE) VALUES (3, 'Ali',  CURRENT_TIMESTAMP);
INSERT INTO CUSTOMERS (ID, NAME, CREATE_DATE) VALUES (4, 'Can',  CURRENT_TIMESTAMP);

INSERT INTO ORDERS (CUSTOMER_ID, PRODUCT_NAME, PRICE) VALUES (1, 'Laptop', 1000);
INSERT INTO ORDERS (CUSTOMER_ID, PRODUCT_NAME, PRICE) VALUES (1, 'Mobile', 1500);
INSERT INTO ORDERS (CUSTOMER_ID, PRODUCT_NAME, PRICE) VALUES (1, 'LCD Monitor', 300);

INSERT INTO ORDERS (CUSTOMER_ID, PRODUCT_NAME, PRICE) VALUES (2, 'Laptop', 1100);
INSERT INTO ORDERS (CUSTOMER_ID, PRODUCT_NAME, PRICE) VALUES (2, 'Mobile', 1650);
INSERT INTO ORDERS (CUSTOMER_ID, PRODUCT_NAME, PRICE) VALUES (2, 'LCD Monitor', 330);

INSERT INTO ORDERS (CUSTOMER_ID, PRODUCT_NAME, PRICE) VALUES (3, 'Laptop', 2000);
INSERT INTO ORDERS (CUSTOMER_ID, PRODUCT_NAME, PRICE) VALUES (3, 'Mobile', 2200);
