INSERT INTO CUSTOMERS (ID, NAME, CREATE_DATE) VALUES (1, 'Ahmet',  CURRENT_TIMESTAMP);
INSERT INTO CUSTOMERS (ID, NAME, CREATE_DATE) VALUES (2, 'Mehmet',  CURRENT_TIMESTAMP);
INSERT INTO CUSTOMERS (ID, NAME, CREATE_DATE) VALUES (3, 'Ali',  CURRENT_TIMESTAMP);
INSERT INTO CUSTOMERS (ID, NAME, CREATE_DATE) VALUES (4, 'Can',  CURRENT_TIMESTAMP);

INSERT INTO ORDERS (CUSTOMER_ID, PRODUCT_NAME, PRICE) VALUES (1, 'Laptop', 1000);
INSERT INTO ORDERS (CUSTOMER_ID, PRODUCT_NAME, PRICE) VALUES (1, 'Mobile', 1500);
INSERT INTO ORDERS (CUSTOMER_ID, PRODUCT_NAME, PRICE) VALUES (1, 'LCD Monitor', 300);

INSERT INTO ORDERS (CUSTOMER_ID, PRODUCT_NAME, PRICE) VALUES (2, 'Laptop', 1100);
INSERT INTO ORDERS (CUSTOMER_ID, PRODUCT_NAME, PRICE) VALUES (2, 'Mobile', 1650);
INSERT INTO ORDERS (CUSTOMER_ID, PRODUCT_NAME, PRICE) VALUES (2, 'LCD Monitor', 330);

INSERT INTO ORDERS (CUSTOMER_ID, PRODUCT_NAME, PRICE) VALUES (3, 'Laptop', 2000);
INSERT INTO ORDERS (CUSTOMER_ID, PRODUCT_NAME, PRICE) VALUES (3, 'Mobile', 2200);

INSERT INTO    NOTIFICATION    (ID, CONTENT, FIRST_NAME, LAST_NAME) VALUES    (1, 'Yaz indirimi', 'Ali', 'ALİOĞLU');
INSERT  INTO     SMS_NOTIFICATION     (PHONE_NUMBER, ID)  VALUES     ('05320000000', 1);

INSERT INTO    NOTIFICATION    (ID, CONTENT, FIRST_NAME, LAST_NAME) VALUES    (2, 'Bedava internet', 'Veli', 'VELİOĞLU');
INSERT  INTO     SMS_NOTIFICATION     (PHONE_NUMBER, ID)  VALUES     ('05420000000', 2);

INSERT INTO    NOTIFICATION    (ID, CONTENT, FIRST_NAME, LAST_NAME) VALUES    (3, 'Java Etkinliği', 'Ahmet', 'AHMETOĞLU');
INSERT  INTO     EMAIL_NOTIFICATION     (EMAIL, ID)  VALUES     ('ahmet@ahmetoglu.com', 3);
